language: python
python:
  - "2.6"
  - "2.7"
install:
  - |
    echo "DATABASES = {'default': {'ENGINE': 'django.contrib.gis.db.backends.postgis', 'NAME': 'travisdb', 'USER': 'postgres'}}" > mapusaurus/mapusaurus/settings/local_settings.py
  - pip install -r requirements.txt --use-mirrors
  - pip install django_coverage coveralls
  - echo "TEST_RUNNER = 'django_coverage.coverage_runner.CoverageRunner'" >> mapusaurus/mapusaurus/settings/local_settings.py
before_script:
  - psql -c 'CREATE DATABASE travisdb;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travisdb
script:
  - cd mapusaurus
  - python manage.py test
after_success:
  - coveralls
